// <auto-generated />
using System;
using Beacon.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beacon.Server.Data.Migrations
{
    [DbContext(typeof(BeaconDbContext))]
    [Migration("20260921205722_ExactProfileAgeAndRemovePronouns")]
    partial class ExactProfileAgeAndRemovePronouns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Beacon.Server.Data.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AdultConfirmedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.BeaconEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AethernetShard")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowPublicLighting")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataCenter")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLitAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LitAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LitByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LitByName")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("LitNote")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LitUntil")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MapX")
                        .HasColumnType("REAL");

                    b.Property<float>("MapY")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<uint>("NearestAetheryteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NearestAetheryteName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubAreaName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("TerritoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesLit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("WorldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataCenter");

                    b.HasIndex("OwnerAccountId");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.HasIndex("TerritoryId");

                    b.HasIndex("WorldId");

                    b.HasIndex("IsLit", "LitUntil");

                    b.HasIndex("IsDeleted", "Visibility", "IsLit");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.BeaconImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BeaconId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UploadedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeaconId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.BeaconLightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BeaconId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExtinguishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LitAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LitUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BeaconId");

                    b.ToTable("Lights");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataCenter")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<long>("LinkedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<uint>("WorldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Name", "WorldId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.FavoriteEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BeaconId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "BeaconId");

                    b.HasIndex("BeaconId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchetypeCsv")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Boundaries")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clan")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataCenter")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .HasMaxLength(4400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMature")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastActiveAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerAvailability")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerContact")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTimezone")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PortraitImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WalkupsWelcome")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("WorldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataCenter");

                    b.HasIndex("OwnerAccountId");

                    b.HasIndex("Race");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.HasIndex("CharacterName", "WorldId")
                        .IsUnique();

                    b.HasIndex("IsDeleted", "Visibility", "LastActiveAt");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileHookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileHooks");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileImages");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConfirmedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OtherProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OtherProfileId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "OtherProfileId")
                        .IsUnique();

                    b.ToTable("ProfileLinks");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Kind", "Value");

                    b.HasIndex("ProfileId", "Kind", "Value")
                        .IsUnique();

                    b.ToTable("ProfileTags");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BeaconId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReporterAccountId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResolvedByAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeaconId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Resolved", "CreatedAt");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.BeaconEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.AccountEntity", "Owner")
                        .WithMany("Beacons")
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.CharacterEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.AccountEntity", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.FavoriteEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.BeaconEntity", "Beacon")
                        .WithMany("Favorites")
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beacon");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.AccountEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileHookEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.ProfileEntity", "Profile")
                        .WithMany("Hooks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileImageEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.ProfileEntity", "Profile")
                        .WithMany("Images")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileLinkEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.ProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileTagEntity", b =>
                {
                    b.HasOne("Beacon.Server.Data.Entities.ProfileEntity", "Profile")
                        .WithMany("Tags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Beacons");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.BeaconEntity", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("Beacon.Server.Data.Entities.ProfileEntity", b =>
                {
                    b.Navigation("Hooks");

                    b.Navigation("Images");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
